// <auto-generated />
namespace CMS.Migrations.CMSContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetagreferences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetagreferences));
        
        string IMigrationMetadata.Id
        {
            get { return "201802141212519_update tag references"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
