// <auto-generated />
namespace CMS.Migrations.CMSContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateassociatedevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateassociatedevent));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291459508_update associated event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
